apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod2
  namespace: argocd
  labels:
    appId: pod2
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/root-apps-app.git
    targetRevision: main
    path: actions/pod2
  destination:
    server: https://kubernetes.default.svc
    namespace: pod2-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
